# Binaries
brew "awscli"
brew "bash" # Bash 4
brew "bat"
brew "composer"
brew "coreutils" # Those that come with macOS are outdated
brew "fnm"
brew "fzf"
brew "git"
brew "git-lfs"
brew "git-extras"
brew "gnupg2"
brew "grep"
brew "httpstat"
brew "jq"
brew "lazygit"
brew "mas"
brew "mtr"
brew "neovim"
brew "pkg-config" # https://github.com/driesvints/dotfiles/issues/20
brew "trash"
brew "tree"
brew "tmux"
brew "watch"
brew "zoxide"
brew "zsh"
brew "zsh-completions"

# Apps
cask "1password"
cask "android-studio"
cask "bartender"
cask "betterdisplay"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "cleanmymac"
cask "cleanshot"
cask "coderunner"
cask "codex"
cask "codex"
cask "cursor"
cask "deckset"
cask "discord"
cask "gcloud-cli"
cask "github"
cask "ghostty"
cask "google-chrome"
cask "granola"
cask "herd"
cask "insomnia"
cask "keybase"
cask "localcan"
cask "logi-options+"
cask "orbstack"
cask "pdf-expert"
cask "pixelsnap"
cask "postico"
cask "postman"
cask "ngrok"
cask "notion"
cask "notion-calendar"
cask "nordvpn"
cask "numi"
cask "minisim"
cask "raycast"
cask "slack"
cask "spotify"
cask "superhuman"
cask "tableplus"
cask "tailscale-app"
cask "telegram"
cask "todoist-app"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "whatsapp"
cask "zoom"

# App store
mas 'Bear', id: 1091189122
mas 'Microsoft Excel', id: 462058435
mas 'Microsoft PowerPoint', id: 462062816
mas 'Microsoft Word', id: 462054704
mas 'Patterns', id: 429449079
mas 'Pixelmator Pro', id: 1289583905
mas 'Unsplash Wallpaper', id: 1284863847
